spring:
  datasource:
    username: myuser@springtest2
    jdbc-url: jdbc:postgresql://mydatabase.postgres.database.azure.com:5432/tododb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: validate
app.demo.todo.load-demo-data: false
logging.level: warn
logging.level.app.demo.todo: warn
