spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  jpa:
    open-in-view: false
server:
  port: ${PORT}
management:
  endpoints:
    enabled-by-default: false #new
    web:
      exposure:
        include: 'health,info,livenessState,readinessState,diskspace,database,prometheus'
  endpoint:
      info:
        enabled: true
      health:
        enabled: true
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true
      diskspace:
        enabled: true
      database:
        enabled: true
      
# https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/actuator.html
# management.health.diskspace.enabled: true
# management.health.database.enabled: true