name: cleanup

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '31 20 * * *'    
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        #see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-cli%2Clinux
        #    az account list-locations -o table

      - name: Set default Azure subscription
        run: az account set -s ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Check the resource group exists
        id: rg_exists
        run: |
          RG_EXISTS=$(az group exists --name ${{ secrets.AZURE_RESOURCE_GROUP }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }})
          echo "::set-output name=RG_EXISTS::${RG_EXISTS}"

      - name: Remove deployed resource group (if exists)
        if: steps.rg_exists.outputs.RG_EXISTS == 'true'
        run: |
          echo "${{ steps.rg_exists.outputs.RG_EXISTS }}"
          az group delete --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }} --yes
      